### PR TITLE
Added the final report readme

### PR DESCRIPTION
**Pull request by professorabhay**
Here is the readme version of the final report!

Ready to merge. 

I'll make a commit in that PR to update the readme file after accomplishing the goal of package creation and documenting the result of the comparison.

### CODE REVIEW

**Comment by mjwilson-google** [comment]
@professorabhay is this ready for review now?

**Comment by professorabhay** [comment]
Yes, It is!

**Review by mjwilson-google — APPROVED** [review]
Looks good overall.

For the performance comparison and packaging guide, were you still planning on adding them to the github wiki?  Either way, it would be good to link to them from this document as well.

**Comment by mjwilson-google** [comment]
I'll merge this now but please either add wiki pages or links to your blog posts about the packaging and comparison, so that we have a record of it in this repo.

**Comment by professorabhay** [comment]
I already created the wiki pages. 
image
image

**Comment by mjwilson-google** [comment]
> I already created the wiki pages.

I see them, thank you!

**Pull request merged**
