### PR TITLE
 Fix functionality of "Turn monitor on/off" button in AudioWorklet Recorder

### PR DESCRIPTION
**Pull request by kk-kd**
#260

### CODE REVIEW

**Comment by kk-kd** [comment]
It will probably be the easiest if I redo this commit... Let me redo it today after work.

**Comment by TenghuiZhang** [comment]
Thank you so much for helping fixing this issue!

**Comment by TenghuiZhang** [comment]
Hi, @kk-kd I just copy your code and run locally. There is a continuous and loud noise happen when the "Turn monitor" is ON (No recording action). Could you please help me verify is that happen on your side too?

**Comment by hoch** [comment]
@TenghuiZhang Since you reviewed this change - could you explain how this change fixes the problem? Also what was the root cause of the issue? I'd be great if we can have that information in the description of the PR. (Or you can simply write it down as a comment.)

**Comment by TenghuiZhang** [comment]
Yeah! This change use the "gain.value" of monitor node to control the visualization graph amplitude. When the minor button is off, the gain.value of monitorNode is 0. When the minor button is on, the gain value will change to 1. Therefore, we are able to control the amplitude of the graph by multiply monitorNode.gain.value. By using this strategy, we can control monitor behavior.

**Review by hoch — APPROVED** [review]
LGTM

**Pull request merged**
