### PR TITLE
Fix functionality of "Turn monitor on/off" button in AudioWorklet Recorder

### PR DESCRIPTION
**Pull request by kk-kd**
https://googlechromelabs.github.io/web-audio-samples/audio-worklet/migration/worklet-recorder/

Right now the "Turn monitor on/off" button on the page isn't controlling monitor behavior. Proposing this patch, but happy to make modifications if you want another behavior.

### CODE REVIEW

**Review by hoch — APPROVED** [review]
Thanks for this contribution!

**Comment by hoch** [comment]
There are some problems with the deployment script. Hopefully we can fix this soon.

**Comment by hoch** [comment]
@TenghuiZhang Could you take a look at this so we can make progress?

**Comment by TenghuiZhang** [comment]
> @TenghuiZhang Could you take a look at this so we can make progress?

@hoch The conflict is fixed. The current check failed due to @kk-kd is not covered CLA. 

Here is a quote link of how to sign the CLA: 
"If you are not currently covered under a CLA, please visit https://cla.developers.google.com/. Once you've signed, follow the "New Contributors" link at the bottom of this page to update this check."

**Comment by kk-kd** [comment]
@TenghuiZhang Can you please take a look which email I have on file? image

**Comment by kk-kd** [comment]
Ah actually I can see it. Unfortunately I was impacted by the Jan layoff and can't sign with my google email anymore lol.

**Pull request closed without merging**
